### PR TITLE
Cl update

### PR DESCRIPTION
**Pull request by Maximellerbach**
added some walls, lightings and props to CircuitLaunch track
here is a preview of the track: 
image

### CODE REVIEW

**Comment by lemketron** [comment]
Hi @Maximellerbach 
We recently enabled the CLA approval on this repository; could you please submit a new PR and accept the CLA which is needed before we can merge the PR?
Thanks!
--Steve

**Comment by Maximellerbach** [comment]
@lemketron Sorry, I don't think I understood properly, what is CLA approval ?
Thanks !

**Comment by lemketron** [comment]
> @lemketron Sorry, I don't think I understood properly, what is CLA approval ? Thanks !

CLA is the Contributor License Agreement that needs to be accepted before we can accept external PRs: 
https://en.wikipedia.org/wiki/Contributor_License_Agreement

It was not initially configured for this repo but has since been added so if you resolve the above conflict (rebase onto master which is now 2021.3) you should be presented with the CLA click-through step.  Thanks!

**Comment by Maximellerbach** [comment]
ok, closing this and reopening the PR to have the CLA step

**Pull request closed without merging**
